---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app
  name: app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.matchLabels.app }}
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: {{ .Values.image.repository }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.port.containerPort }}
        resources: {}
