---
# Source: bakehouse-webapp/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      name: http
      targetPort: 80
      protocol: TCP
  selector:
    app
---
# Source: bakehouse-webapp/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      name: http
      targetPort: 80
      nodeport: 30003
  selector:
    app
---
# Source: bakehouse-webapp/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app
  name: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: kareemelkasaby/itimansbakehouse:7
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources: {}
